import 'server-only';

export type AmbitionGender = 'male' | 'female';

type AmbitionPromptInput = {
  profession: string;
  outfit: string;
  gender: AmbitionGender;
};

const MALE_PROMPT = `Take the provided image of this boy and depict him exactly as he appears — same age, same face, same natural expression — dressed and placed in the world of his dream profession {profession} . Maintain strict identity preservation: same eye shape and spacing, bone structure, skin tone, and ethnicity. The subject must be unmistakably recognizable as themselves. Do not age up, smooth cartoonishly, or drift in any way from the provided face.Preserve the subject's expression precisely as it appears in the input image. Do not exaggerate, widen, or alter the smile. Do not introduce open-mouth grins, exaggerated joy, or any theatrical emotion not present in the original. The expression should feel like a natural continuation of the input — calm, composed, and confident.The subject must remain fully and entirely human. Every part of the body — arms, hands, legs, torso, neck — must look exactly like a normal child's body. Do not alter, replace, modify, or augment any body part under any circumstances. No robotic limbs, mechanical arms, prosthetics, cyborg elements, exoskeleton parts, tech panels, or body modifications of any kind.This applies regardless of the profession. Only clothing and background setting should change.Dress him in accurate, well-fitted {outfit} tailored to fit a child's body naturally — not oversized, not costume-like, not theatrical. Clothing must look worn, real, and proportioned as if it belongs on him. The subject must appear as a full-sized, physically present child occupying the space naturally — not small, not distant, not miniature. Whether the shot is waist-up, three-quarter, or full-body, the subject must fill the frame with natural weight and presence, as a real child would in a professional photograph. The environment should scale around him — backgrounds, furniture, and props should be proportioned to a child of his size, not adult-scaled in a way that makes him appear tiny or doll-like.Place him in an authentic, immersive professional environment with contextually appropriate background elements — real tools, real space. The pose should be natural and relaxed: standing or seated naturally, arms at sides or resting. Do not place props directly in the child's hands unless it is organically and professionally appropriate. Avoid theatrical or staged-looking compositions.Style as a high-end editorial portrait with cinematic lighting, shallow depth of field, sharp facial detail, realistic textures, and natural color grading. The result should feel like a professional photograph — not a composite, not a costume photo, not a fantasy illustration.`;

const FEMALE_PROMPT = `Take the provided image of this girl and depict her exactly as she appears — same age, same face, same natural expression — dressed and placed in the world of her dream profession {profession} . Maintain strict identity preservation: same eye shape and spacing, bone structure, skin tone, and ethnicity. The subject must be unmistakably recognizable as themselves. Do not age up, smooth cartoonishly, or drift in any way from the provided face.
Preserve the subject's expression precisely as it appears in the input image. Do not exaggerate, widen, or alter the smile. Do not introduce open-mouth grins, exaggerated joy, or any theatrical emotion not present in the original. The expression should feel like a natural continuation of the input — calm, composed, and confident.The subject must remain fully and entirely human. Every part of the body — arms, hands, legs, torso, neck — must look exactly like a normal child's body. Do not alter, replace, modify, or augment any body part under any circumstances. No robotic limbs, mechanical arms, prosthetics, cyborg elements, exoskeleton parts, tech panels, or body modifications of any kind. This applies regardless of the profession. Only clothing and background setting should change.Dress her in accurate, well-fitted {outfit} tailored to fit a child's body naturally — not oversized, not costume-like, not theatrical. Clothing must look worn, real, and proportioned as if it belongs on her. Use natural grooming and hair styling appropriate to the profession without altering or masculinizing her appearance. The subject must appear as a full-sized, physically present child occupying the space naturally — not small, not distant, not miniature. Whether the shot is waist-up, three-quarter, or full-body, the subject must fill the frame with natural weight and presence, as a real child would in a professional photograph. The environment should scale around her — backgrounds, furniture, and props should be proportioned to a child of her size, not adult-scaled in a way that makes her appear tiny or doll-like.Place her in an authentic, immersive professional environment with contextually appropriate background elements — real tools, real space. The pose should be natural and relaxed: standing or seated naturally, arms at sides or resting. Do not place props directly in the child's hands unless it is organically and professionally appropriate. Avoid theatrical or staged-looking compositions.Style as a high-end editorial portrait with cinematic lighting, shallow depth of field, sharp facial detail, realistic textures, and natural color grading. The result should feel like a professional photograph — not a composite, not a costume photo, not a fantasy illustration.`;

export const buildAmbitionPrompt = (input: AmbitionPromptInput) => {
  const template = input.gender === 'female' ? FEMALE_PROMPT : MALE_PROMPT;

  return template
    .replace(/\{profession\}/g, input.profession.trim())
    .replace(/\{outfit\}/g, input.outfit.trim());
};