import 'server-only';

export type AmbitionGender = 'male' | 'female';

type AmbitionPromptInput = {
  profession: string;
  outfit: string;
  gender: AmbitionGender;
};

const MALE_PROMPT = `Take the provided image of this boy and depict him exactly as he appears — same age, same face, same natural expression — dressed and placed in the world of his dream profession {profession} . The generated image must be a half-body portrait: from the waist up only. This framing is mandatory regardless of the profession or setting, and ensures the subject appears as a naturally sized, physically present child — never small, distant, or miniature.Maintain strict identity preservation throughout. The boy's face, eye shape and spacing, bone structure, skin tone, and ethnicity must remain identical to the uploaded image. He must be immediately and unmistakably recognizable as the same child. Do not age him up or down, do not smooth his features cartoonishly, and do not allow any identity drift of any kind.The subject must remain completely and entirely human in every part of his body. Arms, hands, shoulders, neck, and torso must look exactly as they do on a real child. Under no circumstances should any body part be replaced, altered, or augmented — no robotic limbs, mechanical arms, cyborg elements, exoskeleton components, tech panels, prosthetics, or any non-human body modification whatsoever. This rule is absolute and applies regardless of the profession selected. Only the clothing and background environment should change.Preserve the subject's expression exactly as it appears in the uploaded image. Do not widen or exaggerate the smile. Do not introduce open-mouth grins, theatrical joy, or any emotion that was not present in the original photo. The face should feel like a calm, natural, proud continuation of the input — composed and real, never performative.Dress him in accurate, well-fitted {outfit} that is properly tailored to a child's body — not oversized, not baggy, not costume-like. The clothing must look genuinely worn and realistically proportioned, as though it naturally belongs on him. Place him in an authentic professional environment appropriate to the selected profession, with real contextually relevant background details that feel immersive and grounded. The pose must be natural and relaxed — no props held in hand unless they occur organically within the professional context. The overall composition must never look theatrical, staged, or like a dress-up photo.Render the final image in the style of a high-end editorial portrait: cinematic lighting, shallow depth of field, sharp detail on the face and upper body, realistic textures, and natural color grading. The result must feel like a real professional photograph of this specific child in this specific profession — not a fantasy, not an illustration, not a composite.
`;

const FEMALE_PROMPT = `Take the provided image of this girl and depict her exactly as she appears — same age, same face, same natural expression — dressed and placed in the world of her dream profession {profession} . The generated image must be a half-body portrait: from the waist up only. This framing is mandatory regardless of the profession or setting, and ensures the subject appears as a naturally sized, physically present child — never small, distant, or miniature.Maintain strict identity preservation throughout. The girl's face, eye shape and spacing, bone structure, skin tone, and ethnicity must remain identical to the uploaded image. She must be immediately and unmistakably recognizable as the same child. Do not age her up or down, do not smooth her features cartoonishly, and do not allow any identity drift of any kind.The subject must remain completely and entirely human in every part of her body. Arms, hands, shoulders, neck, and torso must look exactly as they do on a real child. Under no circumstances should any body part be replaced, altered, or augmented — no robotic limbs, mechanical arms, cyborg elements, exoskeleton components, tech panels, prosthetics, or any non-human body modification whatsoever. This rule is absolute and applies regardless of the profession selected. Only the clothing and background environment should change.Preserve the subject's expression exactly as it appears in the uploaded image. Do not widen or exaggerate the smile. Do not introduce open-mouth grins, theatrical joy, or any emotion that was not present in the original photo. The face should feel like a calm, natural, proud continuation of the input — composed and real, never performative.Dress her in accurate, well-fitted {outfit} that is properly tailored to a child's body — not oversized, not baggy, not costume-like. The clothing must look genuinely worn and realistically proportioned, as though it naturally belongs on her. Use natural grooming and hair styling appropriate to the profession without altering, masculinizing, or changing her appearance in any way. Place her in an authentic professional environment appropriate to the selected profession, with real contextually relevant background details that feel immersive and grounded. The pose must be natural and relaxed — no props held in hand unless they occur organically within the professional context. The overall composition must never look theatrical, staged, or like a dress-up photo.Render the final image in the style of a high-end editorial portrait: cinematic lighting, shallow depth of field, sharp detail on the face and upper body, realistic textures, and natural color grading. The result must feel like a real professional photograph of this specific child in this specific profession — not a fantasy, not an illustration, not a composite.
`;

export const buildAmbitionPrompt = (input: AmbitionPromptInput) => {
  const template = input.gender === 'female' ? FEMALE_PROMPT : MALE_PROMPT;

  return template
    .replace(/\{profession\}/g, input.profession.trim())
    .replace(/\{outfit\}/g, input.outfit.trim());
};